[[redirects]]
  from = "*"
  to = "https://service.prerender.io/https://yp-todo-ssr.netlify.app/"
  status = 200
  conditions = {User-Agent = ["googlebot"]}
  headers = {X-Prerender-Token = "SYLrXoR088zkCXfzZVOC"}
