[[redirects]]
  from = "*"
  to = "https://service.prerender.io/https://yp-todo-ssr.netlify.app/"
  status = 200
  conditions = {Header = {user-agent = "googlebot"}}
  headers = {X-Prerender-Token = "SYLrXoR088zkCXfzZVOC"}
